/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCredentialsRouteImport } from './routes/_authenticated/credentials'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredentialsRoute =
  AuthenticatedCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/trades': typeof AuthenticatedTradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/trades': typeof AuthenticatedTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/credentials': typeof AuthenticatedCredentialsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/credentials'
    | '/dashboard'
    | '/positions'
    | '/settings'
    | '/signals'
    | '/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/credentials'
    | '/dashboard'
    | '/positions'
    | '/settings'
    | '/signals'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/credentials'
    | '/_authenticated/dashboard'
    | '/_authenticated/positions'
    | '/_authenticated/settings'
    | '/_authenticated/signals'
    | '/_authenticated/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credentials': {
      id: '/_authenticated/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthenticatedCredentialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCredentialsRoute: typeof AuthenticatedCredentialsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCredentialsRoute: AuthenticatedCredentialsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
